LogMonitor/src/LogMonitor/Main.cpp

**Repro steps**
1.	Open the LogMonitor solution using Microsoft Visual Studio
2.	Before building the solution, ensure to change the solution platform to x86
3.	Clean and build the solution.
4.	Confirm the errors displayed in the error list
**Explanation**
The bug is related to the difference between __cdecl and __stdcall in x86 and x64. In x64 cdecl and stdcall, are the same, while in x86, cdecl has the caller clean (pop) the stack, while stdcall has the callee clean the stack
**Solution**
This issue can be resolved by using WINAPI. WINAPI is a macro that evaluates to [__stdcall](http://msdn.microsoft.com/en-us/library/zxk0tw93.aspx), a Microsoft-specific keyword that specifies a calling convention where the callee cleans the stack. The function's caller and callee need to agree on a …

resolve x32 build error

---

LogMonitor/LogMonitorTests/LogMonitorTests.vcxproj
LogMonitor/src/LogMonitor/LogMonitor.vcxproj
README.md
azure-pipelines.yml

- Added an x86 Build Job
- Updated build agent to Windows 2022 since 2016 build agents are deprecated
- Upgraded platform toolset to v142(Visual Studio 2019) and Set Windows SDK to 10.0 (latest available)

Add x86 build, update azure build agent and platform toolset

---

LogMonitor/src/LogMonitor/EventMonitor.cpp

'ERROR: Failed to query next event' is displayed when a remote procedure call is cancelled after the GetLastError() function returns ERROR_EVT_UNRESOLVED_VALUE_INSERT. 
This error is captured when a windows event log message contains a %n where n is a number (for example, %1 or %3) in the event description and n is not substituted, the event viewer treats it as an insertion string. 
When this kind of event comes into the probe, the probe will try to retrieve the actual value of %1 or %3. If it can not, it will give the error and leave Summary field as blank
Similar to ERROR_INSUFFICIENT_BUFFER, the ERROR_EVT_UNRESOLVED_VALUE_INSERT should not be handled as an error.
</br>
_Useful link: https://www.ibm.com/support/pages/apar/IV67708_

Handle ERROR_EVT_UNRESOLVED_VALUE_INSERT

---

LogMonitor/src/LogMonitor/Main.cpp
LogMonitor/src/LogMonitor/pch.h

**Issues addressed by PR:** https://github.com/microsoft/windows-container-tools/issues/32, https://github.com/microsoft/windows-container-tools/issues/38
**Repro steps:**
- Run the following on PowerShell:
_$var = @"
{
"LogConfig": {
"sources": [
{
"type": "EventLog",
"startAtOldestRecord": true,
"eventFormatMultiLine": false,
"channels": [
{
"name": "system",
"level": "Error"
}
]
}
]
}
}
"@
$var | Out-File -FilePath "C:\LogMonitor\LogMonitorConfig.json" -Encoding utf8_
- Run LogMonitor.exe
**Solution:**
- Check If the config file is utf-8 encoded and convert
- Remove BOM Character

Convert utf8 encoded configuration file

---

LogMonitor/LogMonitorTests/ConfigFileParserTests.cpp
LogMonitor/LogMonitorTests/LogFileMonitorTests.cpp
LogMonitor/LogMonitorTests/LogMonitorTests.vcxproj
LogMonitor/LogMonitorTests/LogMonitorTests.vcxproj.filters
LogMonitor/LogMonitorTests/Utility.cpp
LogMonitor/LogMonitorTests/Utility.h
LogMonitor/LogMonitorTests/pch.h
LogMonitor/src/LogMonitor/ConfigFileParser.cpp
LogMonitor/src/LogMonitor/Main.cpp
LogMonitor/src/LogMonitor/Parser/ConfigFileParser.h

Currently, the logic to read and convert the config file is part of the StartMonitors function.
The config file reading should be separated from the Monitor function and unit tests created to test the new function.

Refactor StartMonitors

---

LogMonitor/src/LogMonitor/Main.cpp
LogMonitor/src/LogMonitor/ProcessMonitor.cpp

Fixes #36. Did not see the white space thing in VS...
@algamaes @manoj-kadam

Pass through exit code from monitored process to callers of LogMonitor

---

LogMonitor/src/LogMonitor/EtwMonitor.cpp
LogMonitor/src/LogMonitor/EventMonitor.cpp

A trace session controller calls EnableTrace to configure how an ETW event provider logs events to a trace session.
[EnableTrace](https://docs.microsoft.com/en-us/windows/win32/api/evntrace/nf-evntrace-enabletrace) function is obsolete. The [EnableTraceEx2](https://docs.microsoft.com/en-us/windows/desktop/ETW/enabletraceex2) function supersedes this function.
How to refactor : https://docs.microsoft.com/en-us/windows/win32/api/evntrace/nf-evntrace-enabletrace#:~:text=This%20function%20is%20obsolete.%20For,the%20documentation%20for%20EnableTraceEx2.

Refactored from using obsolete EnableTrace to EnableTraceEx2 function

---

LogMonitor/src/LogMonitor/EtwMonitor.cpp
LogMonitor/src/LogMonitor/EtwMonitor.h

The StopTrace function stops the specified event tracing session.
This function is obsolete. Instead, use ControlTrace with ControlCode set to EVENT_TRACE_CONTROL_STOP. The [ControlTrace](https://docs.microsoft.com/en-us/windows/win32/api/evntrace/nf-evntrace-controltracew) function supersedes this function.

Refactored StopTrace function to ControlTrace function

---

CONTRIBUTING.md
README.md

Adds details on:
- How to contribute (generally, not LogMonitor specific, even for future tools)
- How to lint (check for styling issues) locally for LogMonitor
closes #46
closes #50

chore: add contributing guidelines

---

LogMonitor/src/LogMonitor/LogFileMonitor.cpp
LogMonitor/src/LogMonitor/LogFileMonitor.h
LogMonitor/src/LogMonitor/pch.h

- This fixes a bug where some new lines were missing the file name prefix when includeFileNames is enabled. It replaces every new line character with newline + file name prefix.

fix: file monitor source tagging skips some log lines

---

LogMonitor/src/LogMonitor/EtwMonitor.cpp

Output logs appearance. Note **Provide Name** is part of the output 
`	<Source>EtwEvent</Source>
<Time>2022-12-17T18:14:45.000Z</Time>
<Provider Name="Microsoft-Windows-WLAN-Driver"/>
<Provider idGuid="{DAA6A96B-F3E7-4D4D-A0D6-31A350E6A445}"/>
<DecodingSource>DecodingSourceXMLFile</DecodingSource>
<Execution ProcessID="0" ThreadID="0" />
<Level>Information</Level>
<Keyword>0x8000000000000001</Keyword>
<EventID Qualifiers="0">0</EventID>
<EventData>
<FrameUniqueID>9425125</FrameUniqueID>
<PortNumber>0</PortNumber>
<TID>0</TID>
<PeerID>0</PeerID>
<PayloadLength>49</PayloadLength>
<QueueLength>0</QueueLength>
<QueueState>false</QueueState>
<CustomData1>24</CustomData1>
<CustomData2>0</CustomData2>
<CustomData3>0</CustomData3>
`</EventData>``
Sample JSON configuration to used to test this …

include provider name to xml output log for ETW monitoring 

---

LogMonitor/LogMonitorTests/EtwMonitorTests.cpp
LogMonitor/src/LogMonitor/LogMonitor.vcxproj

Task:
Add a unit test to confirm that EtwMonitor level defaults to Error when the level is not provided in the config file.

ETW unit test to check if the EtwMonitor level defaults to Error when the level is not provided

---

LogMonitor/LogMonitorTests/UtilityTests.cpp
LogMonitor/src/LogMonitor/EtwMonitor.cpp
LogMonitor/src/LogMonitor/EtwMonitor.h
LogMonitor/src/LogMonitor/Utility.cpp
LogMonitor/src/LogMonitor/Utility.h

Other output formats can now just be plugged at line 816 with a switch:
/cc. @charitykathure

feat: refactor ETWMonitor code to easily support multiple output formats

---

LogMonitor/src/LogMonitor/ProcessMonitor.cpp

See #121 for details; this is a stop-gap measure for the time being.
===
Coming from the monitored process through the `pipe`:
```
2023-02-27 03:50:18 - DEBUG: Unicode character 161:Â¡''
2023-02-27 03:50:18 - DEBUG: Unicode character 162:'Â¢'
2023-02-27 03:50:18 - DEBUG: Unicode character 163:'Â£'
2023-02-27 03:50:18 - DEBUG: Unicode character 164:'Â¤'
2023-02-27 03:50:18 - DEBUG: Unicode character 165:'Â¥'
2023-02-27 03:50:18 - DEBUG: Unicode character 166:'Â¦'
2023-02-27 03:50:18 - DEBUG: Unicode character 167:'Â§'
2023-02-27 03:50:18 - DEBUG: Unicode character 168:'Â¨'
2023-02-27 03:50:18 - DEBUG: Unicode character 169:'Â©'
2023-02-27 03:50:18 - DEBUG: Unicode character 170:'Âª'
2023-02-27 03:50:18 - DEBUG: Unicode character 171:'Â«'
2023-02-27 03:50:18 - DEBUG: Unicode character …
```

fix: work-around for multi-byte characters

---

LogMonitor/LogMonitorTests/EtwMonitorTests.cpp
LogMonitor/LogMonitorTests/EventMonitorTests.cpp
LogMonitor/LogMonitorTests/LogFileMonitorTests.cpp
LogMonitor/src/LogMonitor/ConfigFileParser.cpp
LogMonitor/src/LogMonitor/EtwMonitor.cpp
LogMonitor/src/LogMonitor/EtwMonitor.h
LogMonitor/src/LogMonitor/EventMonitor.cpp
LogMonitor/src/LogMonitor/EventMonitor.h
LogMonitor/src/LogMonitor/LogFileMonitor.cpp
LogMonitor/src/LogMonitor/LogFileMonitor.h
LogMonitor/src/LogMonitor/Main.cpp
LogMonitor/src/LogMonitor/Parser/LoggerSettings.h
LogMonitor/src/LogMonitor/Utility.cpp
LogMonitor/src/LogMonitor/Utility.h

**Summary**
In addition to getting logs in XML and JSON formats, a user should have the flexibility to customize their windows container logs, dictating how the logs should look like and the specific fields that should appear in log entries.  
For Example: 
To display the timestamp, source, severity and message of an event in STDOUT, a user can specify the following format: 
`[%TimeStamp%] [%Source%] [%Severity%] %Message% `
**Examples:**
**1. Event Logs**
**Configuration:** `"customLogFormat": "[%TimeStamp%] [%Source%] [%Severity%] %Message%"` 
**Output:** _
```
[2023-02-17T02:35:42.000Z] [EventLog] [Information] Successfully logged OS information
```
**2. ETW Logs**
**Configuration:** ` "customLogFormat": "[%TimeStamp%] [%Source%] [%Severity%] [%ProviderId%] [%ProviderName%] [%EventId%] …

Custom Log Format 

---

azure-pipelines.yml

**Tasks:**
Amend the pipeline's Component Governance task to Register OSS vulnerabilities for alerting and work items creation purposes Change the minimum alert severity to warn as 'Low'. (all vulnerabilities equal or greater than Low will be registered, however, alerting level can be configured differently)
**Testing:**
Component Governance page view before running pipeline changes:
Component Governance page view after running pipeline changes:

fix: update component governance step in build pipeline

---

LogMonitor/docs/README.md

Both EventLog examples are missing the required LogConfig and sources parent properties, unlike the other examples.
This change makes both examples valid, so they could be copy-pasted directly into LogMonitorConfig.json

Add missing fields for EventLog examples

---

LogMonitor/src/LogMonitor/EventMonitor.cpp
LogMonitor/src/LogMonitor/LogFileMonitor.cpp
LogMonitor/src/LogMonitor/Utility.cpp
LogMonitor/src/LogMonitor/Utility.h

**Task: Sanitize custom JSON Logs**
For users who might want to specify their own custom JSON log format, they can do so by:
1. Specifying the logFormat as 'custom' 
2. Adding '|json' suffix after the desired custom log format. This is to specify the sanitization method, to aid in validating the log outputs.
Sample configuration:
```
{
"LogConfig": {
"logFormat": "custom",
"sources": [
{
"type": "ETW",
"eventFormatMultiLine": false,
"providers": [
{
"providerName": "Microsoft-Windows-WLAN-Drive",
"providerGuid": "DAA6A96B-F3E7-4D4D-A0D6-31A350E6A445",
"level": "Information"
}
],
"customLogFormat": "{'TimeStamp':'%TimeStamp%', 'source':'%Source%', 'Severity':'%Severity%', 'ProviderId':'%ProviderId%', 'ProviderName':'%ProviderName%', 'EventId':'%EventId%', 'Message':'%Message%'}|json"
}
]
} …
```

Custom JSON Log Sanitization

---

LogMonitor/src/LogMonitor/EtwMonitor.cpp

This change it to help us figure out ETW events failing with 1168: ERROR_NOT_FOUND code.
We do not have a fix at the moment. 
This change is to do the following:
1. Help us identify the ProviderGuid failing with 1168 code
2. Give an informative error message 
3. Help us identify more ETW Providers having this specific failure

Identify the ProviderGuid failing with 1168

---

LogMonitor/LogMonitorTests/ConfigFileParserTests.cpp
LogMonitor/LogMonitorTests/LogFileMonitorTests.cpp
LogMonitor/docs/README.md
LogMonitor/src/LogMonitor/ConfigFileParser.cpp
LogMonitor/src/LogMonitor/FileMonitor/Utilities.cpp
LogMonitor/src/LogMonitor/FileMonitor/Utilities.h
LogMonitor/src/LogMonitor/JsonFileParser.cpp
LogMonitor/src/LogMonitor/LogFileMonitor.cpp
LogMonitor/src/LogMonitor/LogFileMonitor.h
LogMonitor/src/LogMonitor/Main.cpp
LogMonitor/src/LogMonitor/Parser/JsonFileParser.h
LogMonitor/src/LogMonitor/Parser/LoggerSettings.h

If a folder does not exist, wait for a predefined time (user-specified or default). In the logMonitor.json file, we will add a field for wait period, waitInSeconds, which will be the wait time in seconds. The value can range from 0-INFINITY.
-	waitInSeconds = 0
When the value is zero(0), this is means that we do not wait and LogMonitor terminates with an error.
-	waitInSeconds = INFINITY
In this case, LogMonitor will wait for the folder to be created.
-	waitInSeconds = +integer
When the value is a positive integer, LogMonitor will wait for a predefined time. Once the time elapses, LogMonitor will terminate with an error.
**Edge cases:**
- If the user does not specify the value of waitInSeconds, then a default value is used, waitInSeconds = 300, that is, 300seconds (5 minutes).
- If a user …

Add waitInSeconds field to retry if folder/file does not exist

---

sdl-compliance-pipeline.yml

This PR onboards this repo to Secure Development Tools used for running of security and compliance static analysis tools. It adds a YAML file that will be used to create an Azure DevOps pipeline. This pipeline will be triggered by PRs created against the main branch.
1. CodeQL (previously Semmle)
- [CodeQL Portal](https://semmleportal.azurewebsites.net/)
- [CodeQL for YAML-based Azure Pipelines](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/codeql-for-yaml-based-azure-pipelines)
- [CodeQL Build Task](https://eng.ms/docs/microsoft-security/security/azure-security/cloudai-security-fundamentals-engineering/security-integration/guardian-wiki/sdl-azdo-extension/codeql-build-task)
- [Recommended hardware resources for running …

Onboard repo to Secure Development Tools Azure DevOps

---

LogMonitor/src/LogMonitor/EventMonitor.cpp
LogMonitor/src/LogMonitor/EventMonitor.h
LogMonitor/src/LogMonitor/FileMonitor/FileMonitorUtilities.cpp
LogMonitor/src/LogMonitor/FileMonitor/FileMonitorUtilities.h
LogMonitor/src/LogMonitor/LogFileMonitor.cpp
LogMonitor/src/LogMonitor/Utility.cpp
LogMonitor/src/LogMonitor/Utility.h

Error:
New Fix:
This is a quick fix for this bug : https://github.com/microsoft/windows-container-tools/issues/150
All the steps to repro this are in the link above (the image affected, Dockerfile and LogMonitorConfig.json.
Build without the fix:
[LogMonitor.zip](https://github.com/microsoft/windows-container-tools/files/12715852/LogMonitor.zip)
Build with the fix:
[LogMonitorWithFix.zip](https://github.com/microsoft/windows-container-tools/files/12715806/LogMonitorWithFix.zip)

Fix to unblock Event Log failure in runtime:4.8-windowsservercore-ltsc2019 alt

---

LogMonitor/docs/README.md
LogMonitor/src/LogMonitor/FileMonitor/FileMonitorUtilities.cpp
LogMonitor/src/LogMonitor/FileMonitor/FileMonitorUtilities.h
LogMonitor/src/LogMonitor/LogFileMonitor.cpp
LogMonitor/src/LogMonitor/LogFileMonitor.h

This PR fixes LogMonitor tool missing the first few log lines when the log file and directory are created after the LogMonitor tool has started. Issue #170
This regression is caused by the PR [#149](https://github.com/microsoft/windows-container-tools/pull/149). The  WaitForMultipleObjects() function waits until the timer expires even though the object is already created during the wait interval.
The fix adds a waitable object on the directory that the LogMonitor tool is observing. The [WaitForMultipleObjects()](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-waitformultipleobjects) function waits until either the timer expires or the specified file is created. By including the handle of the waitable object in the array, the function can return as soon as the file …

[Fix] Log stream delay when dir does not exist

---

LogMonitor/src/LogMonitor/ProcessMonitor.cpp

Addressing  issue: https://github.com/microsoft/windows-container-tools/issues/171
**Issue Description:**
Log Monitor allows users to specify the log format _(Custom, JSON, or XML)_ for ETW, Event logs, and File logs through the respective sections in the config.json file.
However, in the case of process monitor logs, whose specifications are not captured in the config file, the logs should default to JSON unless the user specifies XML as the desired log format.
In the current implementation _(in  rc2.1.0)_, the default log format is XML unless JSON is specified. This is why when rc2.1.0 users specify `"logFormat": "custom" ` the process monitor logs default to XML format.
For example:
This change ensures that the default log format is `JSON`

fix process monitor formatting

---

LogMonitor/LogMonitorTests/ConfigFileParserTests.cpp
LogMonitor/src/LogMonitor/ConfigFileParser.cpp
LogMonitor/src/LogMonitor/Main.cpp
LogMonitor/src/LogMonitor/Parser/LoggerSettings.h
LogMonitor/src/LogMonitor/ProcessMonitor.cpp
LogMonitor/src/LogMonitor/ProcessMonitor.h
LogMonitor/src/LogMonitor/Utility.cpp
LogMonitor/src/LogMonitor/version.h

**Description:**
[Log Monitor rc2.0.1](https://github.com/microsoft/windows-container-tools/releases/tag/v2.0.1) supports custom log formatting for all log sources (ETW, Event logs, and File logs) except for process monitoring. The main issue has been the lack of configuration options for process monitoring logs. This PR introduces the ability to configure a custom log format for process monitoring.
**Sample Configuration:**
```
{
"LogConfig": {
"logFormat": "custom",
"sources": [
{
"type": "EventLog",
"startAtOldestRecord": true,
"eventFormatMultiLine": false,
"channels": [
{
"name": "system",
"level": "Information"
},
{
"name": "application",
"level": "Error"
}
],
"customLogFormat": "{'TimeStamp':'%TimeStamp%', 'source':'%Source%', 'Severity':'%Severity%', 'EventID':'%EventID%', …
```

Process Monitor Custom Logging

---

LogMonitor/src/LogMonitor/EventMonitor.cpp
LogMonitor/src/LogMonitor/EventMonitor.h

With this change Event Log now has the EventSource entry. Observe the example log emitted with this change.
```
{
"Source": "EventLog",
"LogEntry": {
"EventSource": ".NET Runtime",
"Time": "2024-05-15T23:53:41.000Z",
"Channel": "Application",
"Level": "Error",
"EventId": 1026,
"Message": "Application: VSUpdateHelper.exe\nFramework Version: v4.0.30319\nDescription: The process was terminated due to an unhandled exception.\nException Info: System.Runtime.InteropServices.COMException\n   at Microsoft.VisualStudio.Setup.Services.ProcessService.GetShellDispatchForLoggedInUser()\n   at Microsoft.VisualStudio.Setup.Services.ProcessService.RunAsLoggedOnUser(System.String, System.String)\n   at Microsoft.VisualStudio.Setup.VSUpdateHelper.ToastService.StartProcess(Microsoft.VisualStudio.Setup.ToastN …
```

Include Event Source Name in EventLog Event Log entries

---

LogMonitor/src/LogMonitor/LogFileMonitor.cpp
LogMonitor/src/LogMonitor/LogWriter.h

This PR addresses the following issues:
- we explicitly write wide characters to console and avoid the existing issue where we were taking a performance hit by setting console mode to `utf8` and letting the console implicitly handle the conversion
- file watcher would get stuck when it encounters an empty string and tries to remove a `\n` character. Addressed this by checking for string length first
- WriteConsole writes directly to Console and cannot be redirected, to allow tests to run, added a function to detect console mode and use wprintf when running tests 
fixes: https://github.com/microsoft/windows-container-tools/issues/35

fix file watcher hanging and console write performance

---

LogMonitor/LogMonitorTests/ConfigFileParserTests.cpp
LogMonitor/docs/README.md
LogMonitor/src/LogMonitor/Parser/LoggerSettings.h
LogMonitor/src/LogMonitor/ProcessMonitor.cpp
LogMonitor/src/LogMonitor/ProcessMonitor.h

**Summary of Changes:**
To ensure consistency across various log sources such as Events and File Logs, the process monitor field name has been updated from `Logline` or `LogEntry` to `Message`.
**Testing Instructions:**
Please refer to the testing guidelines provided in this PR: https://github.com/microsoft/windows-container-tools/pull/176
**Test Result:**

Rename Process Monitor Configuration Fields for Consistency

---

LogMonitor/src/LogMonitor/LogWriter.h
LogMonitor/src/LogMonitor/version.h

reverts changes from this [PR](https://github.com/microsoft/windows-container-tools/pull/183). 
- WriteConsoleW output cannot be redirected causing a failure to write to docker logs. 
- Fixes https://github.com/microsoft/windows-container-tools/issues/192

revert: explicitly write wide string characters to console 

---

LogMonitor/docs/README.md

As a recommendation from the previous security review, add an advisory for users on how to restrict write access for the confg file.
This reduces the possibility of the config file being used as an attack vector, especially for a low
privilege user.

logmonitor: docs: add security advisory for config file

---

LogMonitor/src/LogMonitor/JsonFileParser.cpp

The fix involved removing an unnecessary increment (offset++) before advancing the buffer pointer in the ParseNumber() function of your JSON parser. Previously, after parsing a numeric value, the code advanced the offset one extra character, which caused the parser to skip over important JSON structural characters like commas (,) or closing braces (}) that separate or terminate object members. This led to errors when parsing numbers that were not the last member in an object.
By eliminating the extra increment, the parser now correctly leaves the structural character in place for the next parsing step, ensuring proper handling of multi-digit numbers and correct traversal of JSON objects regardless of the order of their members. This change makes the parser robust and compliant with …

Fix JSON parser to correctly handle numeric values
